In [0]:
import torch
from torch.nn import Linear

In [0]:
b = torch.tensor(1.0, requires_grad=True)

In [0]:
def forward(x):
  y = w*x + b
  return y

In [5]:
x = torch.tensor(2)
forward(x)

tensor(7., grad_fn=<AddBackward0>)

In [6]:
x = torch.tensor([[4], [7]])
forward(x)

tensor([[13],
        [22]], grad_fn=<AddBackward0>)

In [9]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [11]:
x = torch.tensor([2.0])
model(x)

tensor([0.5891], grad_fn=<AddBackward0>)

**Creating modules**

In [0]:
import torch.nn as nn

class LR(nn.Module):

  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    pred = self.linear(x)
    return pred

In [17]:
model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2057]], requires_grad=True), Parameter containing:
tensor([0.5087], requires_grad=True)]


In [18]:
x = torch.tensor([1.0])
model.forward(x)

tensor([0.3030], grad_fn=<AddBackward0>)